### ISSUE TITLE
Show label for time on group card

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#114]
## What is the motivation for adding/enhancing this feature?

On the group card, the time should show which time is being shown, for example, created or last updated.

Expected:
<img width="388" alt="Screenshot 2024-02-17 at 9 53 55 AM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/0d4565a9-06f8-447e-8de5-f04bff643fd5">

Current:
<img width="387" alt="Screenshot 2024-02-17 at 9 54 07 AM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/46aeaf67-d7d9-42f9-a6ad-a75b9ac1979b">

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v1.1.0.
https://jam.dev/c/6a629bda-bc59-4deb-a90e-ef41821d66d1
