### ISSUE TITLE
Clicking on status opens routing page

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#115]
## Current behavior

Clicking on the status badge when a routing is active routes the user to the routing detail page. It should toggle the status 'draft' instead which the user can then commit by clicking save.

**Comment by ymaheshwari1** [comment]
Discussed with Aditya Sir, we will allow changing the status from `Active` to `Draft` on clicking the status badge.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.1.0.
https://jam.dev/c/9a1ddb1a-27f2-41cf-8616-8bf38858f38e
