### ISSUE TITLE
Allow multi select on for channels

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#116]
## What is the motivation for adding/enhancing this feature?

User should be allowed to select multiple sales channels:

<img width="536" alt="Screenshot 2024-02-17 at 11 44 48 AM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/b989c3f3-835a-41a7-9797-be2ebca8a058">

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v1.1.0. 
https://jam.dev/c/3a4fd115-d14f-4ffb-bd75-3cf053896deb
