### ISSUE TITLE
Show inventory query status on menu list item

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#117]
## What is the motivation for adding/enhancing this feature?

The menu list items of the inventory lookups should show the status of the look up so that the user knows if the filter is affecting their flow:

<img width="536" alt="Screenshot 2024-02-17 at 12 21 16 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/72235884-633b-4630-b8f1-5eea194ed068">

**Comment by ymaheshwari1** [comment]
Discussed with Aditya Sir, we will display specific status as per the Id instead of displaying `Inactive`.

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v1.1.0.
https://jam.dev/c/e01953bf-780c-4e30-82c8-a67781c41d4c
