### ISSUE TITLE
Rumtime and delta time format

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#118]
## Current behavior

Runtime delta time is not shown in relative format like in job manager.

Also the actual run time should not include seconds, it should be shown in regular format like 4:24pm

<img width="407" alt="Screenshot 2024-02-17 at 3 34 16 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/9905c12f-0a8e-400c-b9be-99aa09879f42">

**Comment by Adameddy26** [comment]
Verified this issue in release v1.1.0 and found that it is not fixed properly. The actual run time is not having time indicators(a.m or p.m).
Hence, reopening this issue.
https://jam.dev/c/7b3d1cc1-66b5-467e-97df-691dd208eddf

**Comment by Adameddy26** [comment]
> Verified this issue in release v1.1.0 and found that it is not fixed properly. The actual run time is not having time indicators(a.m or p.m). Hence, reopening this issue. https://jam.dev/c/7b3d1cc1-66b5-467e-97df-691dd208eddf

Verified this issue in release v1.2.0 and found that it is working fine. Hence, closing this ticket.
https://jam.dev/c/fd90cc78-a133-42a5-bab9-c497750930ef
