### ISSUE TITLE
Remove save alert on Routing Group page

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#119]
## What is the motivation for adding/enhancing this feature?

When saving changes for a Routing Group, the user does not ned to be prompted again to confirm their save.

<img width="1244" alt="Screenshot 2024-02-17 at 7 28 36 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/e37928f0-a081-4e45-8caf-51fb3375683d">

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v1.1.0.
Hence, closing it.
https://jam.dev/c/7c7d66c1-df68-45fd-91e2-01cf0bdacff0
