### ISSUE TITLE
Error history item showing wrong icon

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#120]
## Current behavior

In the Routing history modal, the success icon is being shown even if there are errors in the routing run:

<img width="504" alt="Screenshot 2024-02-17 at 7 38 08 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/85283c02-1368-494a-97ea-1ac563ef7ae2">

**Comment by ymaheshwari1** [comment]
@dt2patel Sir,
The result from the api in this case returns `hasError: "N"` thus we are assuming that there is no error, and hence the icon displayed is of success.

UI in case of error:
![image](https://github.com/hotwax/order-routing-rules/assets/41404838/76790415-aa34-4af2-9040-367b36ed3141)


Response from api in case of error run:
![image](https://github.com/hotwax/order-routing-rules/assets/41404838/4fb31780-565e-42c3-826e-2a1a9a97e326)


Response in the above case:
![image](https://github.com/hotwax/order-routing-rules/assets/41404838/003f87f7-d722-43f6-9d98-06826eda2246)

**Comment by dt2patel** [comment]
discussed and closing task since this is a backend fix
