### ISSUE TITLE
Routing breaks when moving from route list to home page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#124]
## Current behavior

In a specific scenario the apps routing breaks when moving from route list to the home page

## Expected behavior

The routing should always work as expected in all the cases.

## Steps to reproduce the issue

1. Go to the routing list page
2. Select any routing, you will be redirected to the routing details page
3. Refresh the page
4. Click back button, you will be on the routing list page
5. Click back again to move to the home page and you will see that the page is not changed.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
Discussed on this with @dt2patel Sir, we will remove the chip back button and will add the standard ion-back-button on the query page. This change is also a suggestion to have a consistent UI across apps.

Display a full header on query page having a back button and the route name.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.3.0. Hence, closing it.
