### ISSUE TITLE
Missing empty state for Routing, Run Description, and Inventory Rule Fields

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing-rules#142]
## Expected behavior
Empty state texts should be displayed within the routing, run description, and inventory rule fields when no data is present.
Empty state texts should provide clear guidance to users, indicating the purpose of each field and prompting them to enter relevant information.

## Steps to reproduce the issue
Login the application with valid credentials.
Create a new run.
Get inside it to observe the issue for run description and order routing.
Now, get inside any order routing to observe the same issue for inventory rule.
Observe that no empty state texts are displayed within these fields, leaving users uncertain about the expected input.

## Environment details
App version : v1.1.0
App environment : UAT

## Additional information
https://jam.dev/c/e820d31a-85fd-4113-8ef9-8aec81c26ff7

**Comment by ymaheshwari1** [comment]
@dt2patel Sir, we need empty state for specific sections:

- Order batches section
- Inventory Rule
- Inventory Rule detail section: Current Message - `Failed to identify selected inventory rule, please select a rule or refresh`
- Group description

**Comment by dt2patel** [comment]
Routing group / routing run:
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=35729-66869&mode=design&t=yjAE31llpwfSiHhN-11

![BrokeringRunsEmptyState](https://github.com/hotwax/order-routing-rules/assets/60128132/f3f74384-676e-47a1-884b-2237059e8ded)

**Comment by dt2patel** [comment]
Inventory Rule empty state:
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=35731-67589&mode=design&t=yjAE31llpwfSiHhN-11

![InventoryRuleEmptyState](https://github.com/hotwax/order-routing-rules/assets/60128132/dddd781c-ab49-410e-b837-52c4b2338b3e)

**Comment by dt2patel** [comment]
Brokering batch empty state: 
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=35732-70882&mode=design&t=yjAE31llpwfSiHhN-11

**Comment by ymaheshwari1** [comment]
We will display a full button when no description is present.

**Comment by Adameddy26** [comment]
Verified and working fine in release 1.1.0. Hence, closing it.
https://jam.dev/c/82bf2193-ced8-4641-aa9b-57752fca1714
