### ISSUE TITLE
Changes in Rule Settings Not Persisting After Saving.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing-rules#146]
## Expected behavior
After saving changes to the rule settings, they should persist even after navigating away from the page and returning to it.

## Steps to reproduce the issue
Access the rule settings page in the order routing app.
Make changes to the rule settings.
Click on the save button to save the changes.
Navigate away from the page, then return to the rule settings page.
Observe that the previously saved changes are not retained.

## Environment details
App version : MAIN-EE8F630
App environment : DEV

## Additional information
https://jam.dev/c/f76fdd0a-aa78-42cd-bcf9-18f9d30116dc

**Comment by ymaheshwari1** [comment]
The persistence issue is only for proximity filter, all other filters and actions works as expected.
This is only generated when we select proximity in the inventory filters as well as proximity in the inventory sort option. If we only select proximity in the inventory filter, the functionality works as expected.

**Comment by Adameddy26** [comment]
> The persistence issue is only for proximity filter, all other filters and actions works as expected. This is only generated when we select proximity in the inventory filters as well as proximity in the inventory sort option. If we only select proximity in the inventory filter, the functionality works as expected.

Hi @ymaheshwari1 , this issue can be replicated in case of when user creates and modifies multiple rules and save the changes in the last. Please have a look.
https://jam.dev/c/df2b6504-6dc6-46f8-903c-3d4c65ee0036

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.1.0. Hence, closing it.
