### ISSUE TITLE
Product Store name is not visible on UI

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#149]
## Current behavior

When the storeName is not present empty label for select option is displayed on the UI on both runs and settings page

## Expected behavior

If name is not available, productStoreId should be displayed

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://github.com/hotwax/order-routing-rules/assets/41404838/b1db2fe5-bb39-4be8-80f3-a7c8efb26bfd)

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.1.0.
Hence, closing it.
https://jam.dev/c/114c805e-4484-4868-af5a-c80c573b4730
