### ISSUE TITLE
Improved Clarity and Functionality for Promise Date Filter

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/order-routing-rules#155]
## Enhancement Details

- **Improved Display in Filter Chip:**

If a value is entered for a date that has already passed, the chip content should clearly indicate this instead of displaying just '0'.
For values entered for upcoming or passed durations, the chip content should convey this information clearly instead of displaying just the entered value.

- **Highlight Selected Option in Popover:**

Ensure that when a user clicks on the promise date filter chip, the selected option in the popover is highlighted, providing clarity about the selected duration type (passed, already passed date, or upcoming).

- **Display Entered Value in Modal:**

When the user opens the modal by clicking on the popover option to view the entered value, display the chip value in the modal. This allows users to easily take note of the entered value and make any necessary changes.

- **Correct Placeholder in Duration Option Modal:**

Update the placeholder text in the duration option modal from 'duration' to something more appropriate, such as 'Enter Value'. This ensures clarity for users, as they are required to input a single value rather than a range.

- **Rename 'Already Passed' Option in Popover:**

Change the label of the 'Already Passed' option in the popover to 'Already Passed Date'. This clarifies that selecting this option directly displays '0' inside the chip without prompting for a value or duration.

**Comment by Adameddy26** [comment]
@dt2patel Please review the proposed enhancement for the promise date filter and provide decisions on the outlined points. Your input is crucial for ensuring clarity and functionality improvements. Thank you.

**Comment by dt2patel** [comment]
The chip should display a full string based on conditions:

already passed selected: "already passed"
passed duration: "x days passed"
upcoming duration: "upcoming in x days"

<img width="788" alt="Screenshot 2024-04-04 at 9 04 00 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/e1192088-1daf-4600-9ade-336172acbd90">

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v1.1.0. Hence, closing it.
https://jam.dev/c/6260696e-c8a6-4cf6-9577-2d5d3ae9cd7b
