### ISSUE TITLE
Logic to show and hide product stores

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#156]
## What is the motivation for adding/enhancing this feature?

The product store selector should only be visible if there is more than one product store on the OMS instance.

Also lets remove the search runs function, we are not expecting there to ever be so much data here that user actually needs to search.

**Comment by Adameddy26** [comment]
https://github.com/hotwax/order-routing-rules/assets/158989293/c393ab51-3628-46e6-9da9-b7f6202d6828

Issue verified and working fine in release v1.1.0. Hence, closing it
