### ISSUE TITLE
Move "clear auto cancel date" function

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#158]
## What is the motivation for adding/enhancing this feature?

Clearing auto cancel date is only an action for items that were not allocated. So We will no longer have a car for allocated items without splitting. Instead the clear auto cancel date function will be moved to the unavailable items card. This will allow users who want to remove the auto cancel date from items after a certain rule to do so.

Having "remove auto cancel date" disabled and the "days" chip empty will leave the auto cancel date unchanged.

**Comment by ymaheshwari1** [comment]
@dt2patel Sir, just to clarify we will display the chip to enter auto cancel days only when `clear auto cancel days` is off.

**Comment by dt2patel** [comment]
Yes

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v1.1.0. Hence, closing it.
https://jam.dev/c/0a1d587d-cf7a-4449-9f7d-26b43a45738d
