### ISSUE TITLE
Option to clone inventory and routing

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#159]
## What is the motivation for adding/enhancing this feature?

Add option to clone routing and inventory rule. When cloning the new object's name will automatically have "Copy" appended to it

<img width="841" alt="Screenshot 2024-04-04 at 8 12 37 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/64c9dd89-1801-4631-881a-12e636103b37">

<img width="623" alt="Screenshot 2024-04-04 at 8 19 01 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/0ad0b360-5ac2-4885-8ab7-39e1ccaecefa">

**Comment by ymaheshwari1** [comment]
Will add support to clone the route from the details page in the UI upgrade PR.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.1.0. Hence, closing it.
https://jam.dev/c/3db94087-d269-4285-9bc4-3b75081c67a8
