### ISSUE TITLE
Enhance status popover

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#160]
## What is the motivation for adding/enhancing this feature?

New sequence and icons for status popover:

<img width="486" alt="Screenshot 2024-04-04 at 8 55 50 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/8d086f14-496a-441c-bff2-9737a8f2c436">

**Comment by ymaheshwari1** [comment]
Improved the sequence, but didn't added icons as select option is not supporting icons.

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v1.1.0. Hence, closing it.
https://jam.dev/c/02221820-11fc-4a0b-96b8-f0a6798221fe
