### ISSUE TITLE
Remove alert after clicking save

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#161]
## What is the motivation for adding/enhancing this feature?

We don't need an alert after user clicks save on routing detail page.

<img width="1065" alt="Screenshot 2024-04-04 at 11 31 18 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/f06475b2-9899-4781-9d5e-0d9fbf58ce5b">

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release 1.1.0. 
Hence, closing it.
https://jam.dev/c/fe14eef8-5ee1-4697-b7ca-688e5a9c73ac
