### ISSUE TITLE
Prompt user to save when trying to exit view

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#162]
## What is the motivation for adding/enhancing this feature?

Instead of halting the user if they are exiting group page without saving, we should give them an option to save their changes before exiting so that they don't have to go back wards.

<img width="2005" alt="Screenshot 2024-04-04 at 11 35 28 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/4a9961c5-aafe-4ca3-93ff-69586dfc3349">

This can say:

Title: Save changes
Description: Do you want to save your changes before leaving this page?

Left: discard
Right: save

**Comment by Adameddy26** [comment]
Verified this enhancement and found that on clicking outside the alert modal, user is redirected to clicked event without saving the changes.
Instead, modal should get closed on clicking outside of modal.
https://jam.dev/c/73c386ac-25f5-4206-97e4-4c00a3453e62

**Comment by Adameddy26** [comment]
> Verified this enhancement in release v1.1.0 and found that on clicking outside the alert modal, user is redirected to clicked event without saving the changes. Instead, modal should get closed on clicking outside of modal. https://jam.dev/c/73c386ac-25f5-4206-97e4-4c00a3453e62

Verified and working fine in release v1.2.0. Hence, closing it.
https://jam.dev/c/e0b27fb3-27f2-4d10-ab3c-6a49595ef077
