### ISSUE TITLE
Chip with popover doesn't open popover

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#167]
## Current behavior

In a very inconsistent and hard to recreate way, sometimes a popover is not triggered from a chip when the user clicks on it.

https://jam.dev/c/97785687-0cc3-49c4-9757-91f44ef9a4ac

Attached video, could not find consistent way to trigger this though.

**Comment by ymaheshwari1** [comment]
Actually this case can be regenerated when users clicks on the chip and not on the select. This happens in all the places where we have used ion-select inside ion-chip, as the clicking chip does not trigger select option to be displayed.

**Comment by dt2patel** [comment]
interesting, and there is no way to link open select to click of chip

**Comment by ymaheshwari1** [comment]
> interesting, and there is no way to link open select to click of chip

No way OOTB in ionic, but will check if we can find some workaround for this.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.2.0. Hence, closing this ticket.
https://jam.dev/c/4e73ae8c-d693-4422-9dff-aa4e82bb0586
