### ISSUE TITLE
Update UI for the route page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#181]
## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Change 2 - https://jam.dev/c/93361b3f-191c-4c8c-a449-67a5ab756375
Change 3 - https://jam.dev/c/8183a673-97c1-4b0e-8c84-ce2a44ccfb0d
Change 1&4 - https://jam.dev/c/0e857617-1f89-4683-92d2-90cfb2f1510f

All changes of related to updated UI are verified and working fine in release v1.2.0. Hence, closing it.

**Comment by Adameddy26** [comment]
> #182 - https://jam.dev/c/93361b3f-191c-4c8c-a449-67a5ab756375 #182 - https://jam.dev/c/8183a673-97c1-4b0e-8c84-ce2a44ccfb0d #182 - https://jam.dev/c/0e857617-1f89-4683-92d2-90cfb2f1510f #184 & #195 - https://jam.dev/c/6efbdfd3-efac-473b-90fd-b7defbcc0e8c
> 
> All changes of related to updated UI are verified and working fine in release v1.2.0. **Found one issue related to route archive**. To replicate this issue - Archive more than one routings. Open the archived routes modal and then unarchive any one routing. Close the modal to observe the issue.(On closing the modal user is not getting the option to open it again resulting in no presence of archived routings.
> 
> https://jam.dev/c/a71dd76d-c593-4c85-80de-27b8fde78a9a Hence, reopening this ticket.

Issue verified and working fine in release v1.2.1. Hence, closing this ticket.
