### ISSUE TITLE
Add SSO support

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#192]
## What are the acceptance criteria?

- [ ] Enable SSO in order routing using launchpad, use the ofbiz token to login into launchpad

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Additional information

Created a separate branch for this task and do not merge it in main.

**Comment by Adameddy26** [comment]
Verified the enhancement changes and are working fine in release v1.3.0. Hence, closing this ticket.
