### ISSUE TITLE
Add support to filter orders on the basis of facility group and add sort option to sort on the basis of priority

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#216]
## What are the acceptance criteria?

- [ ] Add facility group filter option on orders, display all the facility group and do not need to add any check.
- [ ] Add priority sort option on orders

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.3.0. Hence, closing it.
