### ISSUE TITLE
Option to see run history

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#64]
## What is the motivation for adding/enhancing this feature?

Add UI for user to see the history of a brokering run

**Comment by dt2patel** [comment]
<img width="827" alt="Screenshot 2024-02-06 at 9 19 18 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/f73d3216-725a-46d0-a4cc-eadb99c00d40">
option to view run history

**Comment by ymaheshwari1** [comment]
@dt2patel Sir,
Added support to display the run history, but here I am thinking of adding viewSize of 15 / 20, also I am thinking of moving this history into a modal, as this is not something that user always want to see.
