### ISSUE TITLE
Option to manage Run status cycle

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#66]
## What is the motivation for adding/enhancing this feature?

Each run has a life cycle that needs to be managed:

Scheduled
Status 
- Draft
- Active

And also the option to delete a run

**Comment by dt2patel** [comment]
<img width="1049" alt="Screenshot 2024-02-06 at 9 05 47 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/2b7924e9-6893-42c1-99b1-9fd1597ede21">
@ymaheshwari1 let me know if you have any inputs on this UI

**Comment by ymaheshwari1** [comment]
As per the discussion we won't have option to delete a run, simply we will have a dropdown to change the run status.

**Comment by ymaheshwari1** [comment]
As per the discussion we will have option to select one of the status `Active or Draft`. Also we will have a common `Save` button to save any changes made in the schedule card and status.
When selecting status `Draft`, `isPaused` flag on the schedule becomes `Y` and for active case it will be `N`.

@dt2patel Sir, Which type of runs needs to displayed in the archive modal on the runs page? as we don't manage status on the runs, do we need to display those runs whose schedule has `isPaused` flag as `N`.

**Comment by dt2patel** [comment]
I guess we don't need to manage archive then since we are only managing paused or not. but how will user remove a routing permanently? like if they don't want to see it in their view anymore etc @dixitdeepak thoughts?

**Comment by ymaheshwari1** [comment]
Added support to change the run status, but as we do not have support to delete a run, so not closing this issue.

**Comment by dt2patel** [comment]
need to discuss run separately, will close this for now
