### ISSUE TITLE
Unable to select partial allocation

### ISSUE THREAD

**Issue by dt2patel** [hotwax/order-routing-rules#68]
When configuring my rules there was a situation where I was not allowed to enable partial allocation. We should tell the user why it is not enabled because right now I was not able to think of a reason for it to be disabled

https://order-routing-dev.hotwax.io/tabs/brokering/PRE_ORDER_GROUP/100307/rules

dev instance

<img width="709" alt="Screenshot 2024-02-01 at 8 19 51 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/1cf2e08b-7c8e-46be-b3f0-52ec8e362fa8">

**Comment by ymaheshwari1** [comment]
Hi @dt2patel Sir,
Yes, we can add a tooltip or a warning message here to tell the user about the case when they can't select partial allocation option.
As discussed with Deepak Sir, partial allocation will not work when user have selected promise date filter, thus its disabled in that case.

**Comment by dt2patel** [comment]
We can add a message below the toggle item:

"Partial allocation cannot be disabled. Orders are filtered by item when filtering by promise date."

Also need to make sure that it shows as toggled on but in disabled state.

**Comment by ymaheshwari1** [comment]
> We can add a message below the toggle item:
> 
> "Partial allocation cannot be disabled. Orders are filtered by item when filtering by promise date."
> 
> Also need to make sure that it shows as toggled on but in disabled state.

So, here we are saying that when `Promise date` filter is selected, the `Partial Allocation` will be enabled even if that was not previously enabled, but this change in `Partial allocation` action will not be saved, just we will show it on the UI, right?

**Comment by ymaheshwari1** [comment]
> > We can add a message below the toggle item:
> > "Partial allocation cannot be disabled. Orders are filtered by item when filtering by promise date."
> > Also need to make sure that it shows as toggled on but in disabled state.
> 
> So, here we are saying that when `Promise date` filter is selected, the `Partial Allocation` will be enabled even if that was not previously enabled, but this change in `Partial allocation` action will not be saved, just we will show it on the UI, right?

@dt2patel Sir, need you inputs on this, currently UI looks like [this](https://private-user-images.githubusercontent.com/41404838/303291392-09da35c0-262c-47c8-91aa-b7f836b42395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODkyNzMsIm5iZiI6MTcwNzM4ODk3MywicGF0aCI6Ii80MTQwNDgzOC8zMDMyOTEzOTItMDlkYTM1YzAtMjYyYy00N2M4LTkxYWEtYjdmODM2YjQyMzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEwNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZDYwNTcyYjQ0ODgyMzljMzAwNWE4NzJmNTJhMjA3NWE3OWQxZGI4OTY0Y2ZlNmJhYzM3YTI1ZDU2NDc3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C_E4oaq-BTskzuOuByEOF6SbvSqTorRTu00GR8GOTVM) in case of promise date filter is selected, but we don't mark partial allocation as checked, as it was not selected before applying promise date filter.
