### ISSUE TITLE
Icon and favicon for routing app

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#74]
## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
![Brokering](https://github.com/hotwax/order-routing-rules/assets/60128132/607653a8-cf64-475a-9045-274bada743d3)
![Brokering](https://github.com/hotwax/order-routing-rules/assets/60128132/9da1f25f-4be7-437b-9a4a-f017ae2d901e)

**Comment by Adameddy26** [comment]
changes verified and working fine in release v1.1.0.
Hence, closing it.
