### ISSUE TITLE
Add support for multiple shipping method selection in order filters

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#83]
## What is the motivation for adding/enhancing this feature?

User should be able to select multiple shipping method when applying order filters

## What are the acceptance criteria?

- [x] When selecting more than one shipping method the operator passed should be `in`.
- [x] When selecting a single shipping method the operator passed should be `equals`
- [x] When a single method is selected, the name of the method needs to displayed
- [ ] When multiple shipping method is selected, count of the total methods needs to be displayed

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
@dt2patel Sir, Please add your inputs on this.

**Comment by dt2patel** [comment]
I agree. We should think of good UI for this. Does popover allow multi select? Or does it only allow single select. Maybe we can use alert instead?

**Comment by ymaheshwari1** [comment]
> I agree. We should think of good UI for this. Does popover allow multi select? Or does it only allow single select. Maybe we can use alert instead?

Popover has support for multiple selection, and its UI will have checkboxes before the name.

**Comment by ymaheshwari1** [comment]
> > I agree. We should think of good UI for this. Does popover allow multi select? Or does it only allow single select. Maybe we can use alert instead?
> 
> Popover has support for multiple selection, and its UI will have checkboxes before the name.

@dt2patel Sir, Should we move ahead with this?

**Comment by dt2patel** [comment]
Yes this is good, sorry for the late reply
