### ISSUE TITLE
Support to display the run history for each route

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/order-routing-rules#85]
## What is the motivation for adding/enhancing this feature?

Currently, we have a feature to display the history for runs, but we need some way to see the history for specific routes as well.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
@dt2patel Sir, proposed design for this feature.

https://www.figma.com/file/1zV3igEzA2OFHE6tqCmSGH/HC-Ionic-design-system-(Copy)?type=design&node-id=35905-7099&mode=design&t=dBvfPEYLOEAosJuq-0

**Comment by dt2patel** [comment]
what are the details that will be presented in the route history?

**Comment by ymaheshwari1** [comment]
> what are the details that will be presented in the route history?

It will display the details like startTime, endTime, any error in the route and route result.

**Comment by dt2patel** [comment]
<img width="701" alt="Screenshot 2024-02-11 at 10 02 06 PM" src="https://github.com/hotwax/order-routing-rules/assets/60128132/96f98c42-d6b2-43ab-ad5e-c71620c83a47">
Clicking on chip from group or routing page will open the history modal
